# Generated by Django 5.0 on 2023-12-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backet',
            name='token',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
